# Generated by Django 4.1 on 2024-08-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='latest_vote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='latest_vote',
            old_name='vote_logs_id',
            new_name='vote_logs',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='vote_log',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='vote_log',
            old_name='user_id',
            new_name='user',
        ),
    ]
