# Generated by Django 4.1 on 2024-08-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_category_category_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latest_vote',
            old_name='vote_logs',
            new_name='vote_log',
        ),
    ]
