# Generated by Django 4.1 on 2024-08-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_vote_logs_latest_vote_vote_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
