# Generated by Django 4.1 on 2024-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_voter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
