# Generated by Django 4.1 on 2024-09-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_plan_plan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='latest_vote',
            options={'verbose_name_plural': '最新投票'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': '企画'},
        ),
        migrations.AlterModelOptions(
            name='vote_log',
            options={'verbose_name_plural': '投票履歴'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name_plural': '有権者'},
        ),
    ]
