# Generated by Django 4.1 on 2024-10-12 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_options_alter_latest_vote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='group',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
